service:
    database:
        # dsn: "dsn"
    server:
        # production: false
        # logfile: ""
        # port: 8080
        handler_timeout_in_seconds: 2
        shutdown_timeout_in_seconds: 3

    token:
        # secret_key: "secret_key"
        access:
            duration:
                in_minutes: 180
        refresh:
            duration:
                in_minutes: 504000
    
    elasticsearch:
        url: "http://localhost:9200"
        
      
pagination:
    page:
        var_name: 'page'
        min_value: 1
    page_size:
            var_name: 'per_page'
            default_value: 100
            min_value: 1
            max_value: 1000

validation:
    anchored_fields:
        date: &date
            min_value:
                year: 1850
                month: 1
                day: 1
        name: &name
            min_length: 3
            max_length: 20
        bio: &bio
            min_length: 3
            max_length: 500
        title: &title
            min_length: 3
            max_length: 100
        descriptions: &descriptions
            min_length: 3
            max_length: 500
        number: &number
            max_value: 1000

    request:
        search:
            query:
                min_length: 1
                max_length: 200
        invalidation:
            min_length: 10
            max_length: 100
        array:
            max_length: 1000

    user:
        email:
            min_length: 8
            max_length: 40
        password:
            min_length: 8
            max_length: 40
            required_numbers: 2
            required_lower_letters: 2
            required_upper_letters: 2
            required_special_chars: 1
        first_name: *name
        last_name: *name
        bio: *bio
        birthdate: *date
    
    film:
        title: *title
        descriptions: *descriptions
        date_released: *date
        duration:
            min_length: 60
            max_length: 100000
        episode_number: *number
        season_number: *number

    series:
        title: *title
        descriptions: *descriptions
        date_started: *date
        date_ended: *date