name: Tests

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: elasticsearch:8.4.0
        env:
          discovery.type=single-node
          xpack.security.enabled=false
          bootstrap.memory_lock=true
        ports:
          - 9200:9200
        options: --health-cmd curl -s -I http://localhost:9200 | grep -q 'HTTP/1.1 200 OK' --health-interval 10s --health-timeout 5s --health-retries 5
    
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...
      
    - name: Set up postgres
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '14'

    - name: Test
      run: make test-all
